# Generated by Django 5.1.4 on 2024-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link_1', models.URLField(blank=True, max_length=500, null=True)),
                ('link_2', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
